# Generated by Django 4.2.9 on 2025-09-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_type',
        ),
    ]
