# Generated by Django 4.2.9 on 2025-09-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patientprofile_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasurement',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], help_text='Physical activity level', max_length=20, null=True),
        ),
    ]
