# Generated by Django 4.2.9 on 2025-09-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=20),
        ),
    ]
