# Generated by Django 4.2.9 on 2025-09-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_patientprofile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasurement',
            name='adjusted_body_weight',
            field=models.FloatField(blank=True, help_text='Adjusted Body Weight calculated automatically', null=True),
        ),
    ]
