# Generated by Django 4.2.9 on 2025-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='daily_calories',
            field=models.IntegerField(blank=True, help_text='Daily calorie intake target', null=True),
        ),
    ]
