# Generated by Django 4.2.9 on 2025-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Patient'), ('delivered', 'Meal Plan Delivered'), ('acknowledged', 'Patient Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
