# Generated by Django 4.2.9 on 2025-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_mealplan_acknowledged_at_mealplan_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='diet_plan',
            field=models.CharField(blank=True, help_text='النظام الغذائي المتكامل المختار', max_length=50, null=True),
        ),
    ]
