# Generated by Django 4.2.9 on 2025-10-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plans', '0003_mealplan_diet_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMealSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('breakfast', 'الإفطار'), ('lunch', 'الغداء'), ('dinner', 'العشاء'), ('snack', 'وجبة خفيفة')], max_length=50)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='meal_plans.mealplan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-selected_at'],
                'unique_together': {('patient', 'meal_plan', 'meal_name', 'meal_type', 'selected_at')},
            },
        ),
    ]
