# Generated by Django 4.2.9 on 2025-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_patientmealselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmealselection',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, help_text='List of ingredients with amounts'),
        ),
    ]
