# Generated by Django 4.2.9 on 2025-11-09 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plans', '0005_patientmealselection_ingredients'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientmealselection',
            unique_together={('patient', 'meal_plan', 'meal_name', 'meal_type')},
        ),
    ]
