# Generated by Django 4.2.9 on 2025-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
